### ISSUE TITLE
复制内容出错

### ISSUE THREAD

**Issue by PythonSmall-Q** [langningchen/XMOJ-Script#9]
![image](https://github.com/langningchen/XMOJ-Script/assets/106425289/efdc9f42-3fd8-4a6d-8147-6dbab6ad8ed6)
根据
https://github.com/langningchen/XMOJ-Script/blob/01572d0502168dfbfaaea9e92159cc6610c7e8ae/XMOJ.user.js#L1906
到
https://github.com/langningchen/XMOJ-Script/blob/01572d0502168dfbfaaea9e92159cc6610c7e8ae/XMOJ.user.js#L1910C31-L1910C31
段的内容，null部分获取失败

**Comment by langningchen** [comment]
In order to reduce the stress of server, the data is got passively. The data comes from here. https://github.com/langningchen/XMOJ-Script/blob/01572d0502168dfbfaaea9e92159cc6610c7e8ae/XMOJ.user.js#L652C8-L652C8
Please ensure that you visit the contest stats page (http://www.xmoj.tech/status.php) to get the data.

**Comment by PythonSmall-Q** [comment]
emm还是错误

**Comment by PythonSmall-Q** [comment]
依旧是null

**Comment by langningchen** [comment]
There isn't anything wrong with my browser. Can you provide some more information such as a screenshot of the console(F12)?

**Comment by PythonSmall-Q** [comment]
ahh forget it. 我还是每次手打字吧

**Comment by PythonSmall-Q** [comment]
顺便问一声那个查看别人数据是怎么玩的

**Comment by langningchen** [comment]
> 顺便问一声那个查看别人数据是怎么玩的

Please go to discuss, which will be open soon.

**Comment by langningchen** [comment]
The issue is an error on your end. Not the script.
